attendance:
  userName: 13559489067
  passWord: C4CA4238A0B923820DCC509A6F75849B
  serviceUrl: http://localhost:8086
wechat:
  openId: okMOL1aH0-WDPpaLMYgMd59HQ5L4
  templateId: 3TfikE2jG-n1qy3dVVAkuVusFaT-Dnt_PrFTO1ZDGyM
  serviceUrl: https://weixin.0be.cn
  flag: jxw
  weAppFlag: xjwWeAppTest
  appid: micro_lsxjy
  secret: micro_lsxjy