attendance:
  userName: 13559489067
  passWord: a3672d1a3ee5ffc11a1ead9d4953acc1
  serviceUrl: http://nsysapi.lsxjy.com.cn
  scheduled:
    morning: ${attendance.scheduled.seconds} ${attendance.scheduled.morningMinute} 8 * * ? #八点10分到29分，指定秒
    noon: ${attendance.scheduled.seconds} ${attendance.scheduled.noonMinute} 12 * * ?
    afternoon: ${attendance.scheduled.seconds} ${attendance.scheduled.afternoonMinute} 20 * * ?
    seconds: 1,3,7,16,19,20,28,33,41,49,50,58
    morningMinute: 1-20
    noonMinute: 1-10
    afternoonMinute: 1-59
wechat:
  openId: odvHvjjoC-BhhCsBqK4WxgwfPTVY
  templateId: TKvg5RroCqnF8l5mZ-qlMEO0LVA9g3Oka1a5FATWywg
  serviceUrl: https://wx.lsxjy.com.cn
  flag: xjwflag
  weAppFlag: XjwUniApp
  appid: micro_lsxjy
  secret: micro_lsxjy
  messageUrl: http//:121.41.13.216:${server.port}/wanglonghai/doAttendance?timeTime=morning