users:
  list:
    - {name: 13559489067,pwd: 5e73fefa762139c1cb3c5f22e42f9320,openId: oLo0Q5zFF6SRzevmEwVkF18jDH74,tk: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJMT0dJTl9VU0VSX0tFWSI6InBjM2RjNWEwNzEzYmVkNGM0ZjlkNmQzNmI0ZjJjZWM4MTQifQ.RTFf1XcAhiPsRY_tlvhFQhZUHlMRqYZ_PAYRpfGorVc}
attendance:
  serviceUrl: http://nsysapi.yongxinjia.com
  summary:
    scheduled: 1 13 23 * * ?
  scheduled:
    morning: ${attendance.scheduled.seconds} ${attendance.scheduled.morningMinute} 8 * * ? #八点10分到29分，指定秒
    noon: ${attendance.scheduled.seconds} ${attendance.scheduled.noonMinute} 12 * * ?
    afternoon: ${attendance.scheduled.seconds} ${attendance.scheduled.afternoonMinute} 20 * * ?
    seconds: 1,3,7,16,19,20,28,33,41,49,50,58
    morningMinute: 1-25
    noonMinute: 1-10
    afternoonMinute: 1-59
wechat:
  templateId: TKvg5RroCqnF8l5mZ-qlMEO0LVA9g3Oka1a5FATWywg
  serviceUrl: https://wx.yongxinjia.com
  flag: xjwflag
  weAppFlag: XjwUniApp
  appid: micro_lsxjy
  secret: micro_lsxjy
  messageUrl: 121.41.13.216:${server.port}/
