users:
  list:
    - {name: 13559489067,pwd: C4CA4238A0B923820DCC509A6F75849B,openId: okMOL1aH0-WDPpaLMYgMd59HQ5L4}
    - {name: xxx,pwd: xxx,openId: }
attendance:
  serviceUrl: http://localhost:8086
  summary:
    scheduled:  1 13 23 * * ?
  scheduled:
    morning: ${attendance.scheduled.seconds} ${attendance.scheduled.morningMinute} 11 * * ? #八点10分到29分，指定秒
    noon: ${attendance.scheduled.seconds} ${attendance.scheduled.noonMinute} 12 * * ?
    afternoon: ${attendance.scheduled.seconds} ${attendance.scheduled.afternoonMinute} 20 * * ?
    seconds: 1,3,7,16,19,20,28,33,41,49,50,58
    morningMinute: 1-25
    noonMinute: 1-10
    afternoonMinute: 1-59
wechat:
  templateId: 3TfikE2jG-n1qy3dVVAkuVusFaT-Dnt_PrFTO1ZDGyM
  serviceUrl: https://weixin.0be.cn
  flag: jxw
  weAppFlag: xjwWeAppTest
  appid: micro_lsxjy
  secret: micro_lsxjy
  messageUrl: 121.41.13.216:${server.port}/
